[package]
name = "kicin-io"
version = "0.1.0"
authors = ["TheAdnan <adnankicin92@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates", "tera_templates"]
